//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 06/01/2021 05:39:02
namespace Api.Models
{
        /// <summary>
        /// There are no comments for CategorySingle in the schema.
        /// </summary>
    public partial class CategorySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Category>
    {
        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CategorySingle object.
        /// </summary>
        public CategorySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Category> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Vehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> Vehicles
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Vehicles == null))
                {
                    this._Vehicles = Context.CreateQuery<global::Api.Models.Vehicle>(GetPath("Vehicles"));
                }
                return this._Vehicles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> _Vehicles;
    }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Category : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Category CreateCategory(int ID, global::System.DateTimeOffset createdOn)
        {
            Category category = new Category();
            category.Id = ID;
            category.CreatedOn = createdOn;
            return category;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTimeOffset value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property Vehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle> Vehicles
        {
            get
            {
                return this._Vehicles;
            }
            set
            {
                this.OnVehiclesChanging(value);
                this._Vehicles = value;
                this.OnVehiclesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle> _Vehicles = new global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle>();
        partial void OnVehiclesChanging(global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle> value);
        partial void OnVehiclesChanged();
    }
        /// <summary>
        /// There are no comments for ManufacturerSingle in the schema.
        /// </summary>
    public partial class ManufacturerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Manufacturer>
    {
        /// <summary>
        /// Initialize a new ManufacturerSingle object.
        /// </summary>
        public ManufacturerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ManufacturerSingle object.
        /// </summary>
        public ManufacturerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ManufacturerSingle object.
        /// </summary>
        public ManufacturerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Manufacturer> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Vehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> Vehicles
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Vehicles == null))
                {
                    this._Vehicles = Context.CreateQuery<global::Api.Models.Vehicle>(GetPath("Vehicles"));
                }
                return this._Vehicles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> _Vehicles;
    }
        /// <summary>
        /// There are no comments for Manufacturer in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Manufacturer : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Manufacturer object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Manufacturer CreateManufacturer(int ID, global::System.DateTimeOffset createdOn)
        {
            Manufacturer manufacturer = new Manufacturer();
            manufacturer.Id = ID;
            manufacturer.CreatedOn = createdOn;
            return manufacturer;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTimeOffset value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property Vehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle> Vehicles
        {
            get
            {
                return this._Vehicles;
            }
            set
            {
                this.OnVehiclesChanging(value);
                this._Vehicles = value;
                this.OnVehiclesChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle> _Vehicles = new global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle>();
        partial void OnVehiclesChanging(global::System.Collections.ObjectModel.Collection<global::Api.Models.Vehicle> value);
        partial void OnVehiclesChanged();
    }
        /// <summary>
        /// There are no comments for VehicleSingle in the schema.
        /// </summary>
    public partial class VehicleSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Vehicle>
    {
        /// <summary>
        /// Initialize a new VehicleSingle object.
        /// </summary>
        public VehicleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VehicleSingle object.
        /// </summary>
        public VehicleSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VehicleSingle object.
        /// </summary>
        public VehicleSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Vehicle> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Api.Models.CategorySingle Category
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Category == null))
                {
                    this._Category = new global::Api.Models.CategorySingle(this.Context, GetPath("Category"));
                }
                return this._Category;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Api.Models.CategorySingle _Category;
        /// <summary>
        /// There are no comments for Manufacturer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Api.Models.ManufacturerSingle Manufacturer
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Manufacturer == null))
                {
                    this._Manufacturer = new global::Api.Models.ManufacturerSingle(this.Context, GetPath("Manufacturer"));
                }
                return this._Manufacturer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Api.Models.ManufacturerSingle _Manufacturer;
    }
        /// <summary>
        /// There are no comments for Vehicle in the schema.
        /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Vehicle : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Vehicle object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="engine">Initial value of Engine.</param>
        /// <param name="year">Initial value of Year.</param>
        /// <param name="seats">Initial value of Seats.</param>
        /// <param name="doors">Initial value of Doors.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Vehicle CreateVehicle(int ID, 
                    int engine, 
                    int year, 
                    int seats, 
                    int doors, 
                    global::System.DateTimeOffset createdOn)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.Id = ID;
            vehicle.Engine = engine;
            vehicle.Year = year;
            vehicle.Seats = seats;
            vehicle.Doors = doors;
            vehicle.CreatedOn = createdOn;
            return vehicle;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CategoryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> CategoryId
        {
            get
            {
                return this._CategoryId;
            }
            set
            {
                this.OnCategoryIdChanging(value);
                this._CategoryId = value;
                this.OnCategoryIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CategoryId;
        partial void OnCategoryIdChanging(global::System.Nullable<int> value);
        partial void OnCategoryIdChanged();
        /// <summary>
        /// There are no comments for Property ManufacturerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> ManufacturerId
        {
            get
            {
                return this._ManufacturerId;
            }
            set
            {
                this.OnManufacturerIdChanging(value);
                this._ManufacturerId = value;
                this.OnManufacturerIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ManufacturerId;
        partial void OnManufacturerIdChanging(global::System.Nullable<int> value);
        partial void OnManufacturerIdChanged();
        /// <summary>
        /// There are no comments for Property Generation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Generation
        {
            get
            {
                return this._Generation;
            }
            set
            {
                this.OnGenerationChanging(value);
                this._Generation = value;
                this.OnGenerationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Generation;
        partial void OnGenerationChanging(string value);
        partial void OnGenerationChanged();
        /// <summary>
        /// There are no comments for Property Engine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Engine
        {
            get
            {
                return this._Engine;
            }
            set
            {
                this.OnEngineChanging(value);
                this._Engine = value;
                this.OnEngineChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Engine;
        partial void OnEngineChanging(int value);
        partial void OnEngineChanged();
        /// <summary>
        /// There are no comments for Property Model in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this._Model = value;
                this.OnModelChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        /// <summary>
        /// There are no comments for Property BodyType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string BodyType
        {
            get
            {
                return this._BodyType;
            }
            set
            {
                this.OnBodyTypeChanging(value);
                this._BodyType = value;
                this.OnBodyTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BodyType;
        partial void OnBodyTypeChanging(string value);
        partial void OnBodyTypeChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Year;
        partial void OnYearChanging(int value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Property Seats in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Seats
        {
            get
            {
                return this._Seats;
            }
            set
            {
                this.OnSeatsChanging(value);
                this._Seats = value;
                this.OnSeatsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Seats;
        partial void OnSeatsChanging(int value);
        partial void OnSeatsChanged();
        /// <summary>
        /// There are no comments for Property Doors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Doors
        {
            get
            {
                return this._Doors;
            }
            set
            {
                this.OnDoorsChanging(value);
                this._Doors = value;
                this.OnDoorsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Doors;
        partial void OnDoorsChanging(int value);
        partial void OnDoorsChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTimeOffset value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Api.Models.Category Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Api.Models.Category _Category;
        partial void OnCategoryChanging(global::Api.Models.Category value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property Manufacturer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Api.Models.Manufacturer Manufacturer
        {
            get
            {
                return this._Manufacturer;
            }
            set
            {
                this.OnManufacturerChanging(value);
                this._Manufacturer = value;
                this.OnManufacturerChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Api.Models.Manufacturer _Manufacturer;
        partial void OnManufacturerChanging(global::Api.Models.Manufacturer value);
        partial void OnManufacturerChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Api.Models.Category as global::Api.Models.CategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Api.Models.CategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Category> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Api.Models.CategorySingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Api.Models.Category as global::Api.Models.CategorySingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Api.Models.CategorySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Category> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Api.Models.CategorySingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Api.Models.Manufacturer as global::Api.Models.ManufacturerSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Api.Models.ManufacturerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Manufacturer> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Api.Models.ManufacturerSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Api.Models.Manufacturer as global::Api.Models.ManufacturerSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Api.Models.ManufacturerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Manufacturer> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Api.Models.ManufacturerSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Api.Models.Vehicle as global::Api.Models.VehicleSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Api.Models.VehicleSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Api.Models.VehicleSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Api.Models.Vehicle as global::Api.Models.VehicleSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Api.Models.VehicleSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Api.Models.VehicleSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Api.Models.OData.Actions
{
        /// <summary>
        /// There are no comments for ActionForCategory in the schema.
        /// </summary>
    public partial class ActionForCategory
    {
        /// <summary>
        /// Create a new ActionForCategory object.
        /// </summary>
        /// <param name="manufacturerId">Initial value of ManufacturerId.</param>
        /// <param name="engine">Initial value of Engine.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ActionForCategory CreateActionForCategory(int manufacturerId, int engine)
        {
            ActionForCategory actionForCategory = new ActionForCategory();
            actionForCategory.ManufacturerId = manufacturerId;
            actionForCategory.Engine = engine;
            return actionForCategory;
        }
        /// <summary>
        /// There are no comments for Property ManufacturerId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int ManufacturerId
        {
            get
            {
                return this._ManufacturerId;
            }
            set
            {
                this.OnManufacturerIdChanging(value);
                this._ManufacturerId = value;
                this.OnManufacturerIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ManufacturerId;
        partial void OnManufacturerIdChanging(int value);
        partial void OnManufacturerIdChanged();
        /// <summary>
        /// There are no comments for Property Engine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Engine
        {
            get
            {
                return this._Engine;
            }
            set
            {
                this.OnEngineChanging(value);
                this._Engine = value;
                this.OnEngineChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Engine;
        partial void OnEngineChanging(int value);
        partial void OnEngineChanged();
    }
}
namespace System.Linq
{
        /// <summary>
        /// There are no comments for IQueryable_1OfVehicleCountForCategory in the schema.
        /// </summary>
    public abstract partial class IQueryable_1OfVehicleCountForCategory
    {
    }
        /// <summary>
        /// There are no comments for IQueryable_1OfYearForVehicle in the schema.
        /// </summary>
    public abstract partial class IQueryable_1OfYearForVehicle
    {
    }
}
namespace Default
{
        /// <summary>
        /// There are no comments for Container in the schema.
        /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Category> Categories
        {
            get
            {
                if ((this._Categories == null))
                {
                    this._Categories = base.CreateQuery<global::Api.Models.Category>("Categories");
                }
                return this._Categories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Category> _Categories;
        /// <summary>
        /// There are no comments for Producers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Manufacturer> Producers
        {
            get
            {
                if ((this._Producers == null))
                {
                    this._Producers = base.CreateQuery<global::Api.Models.Manufacturer>("Producers");
                }
                return this._Producers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Manufacturer> _Producers;
        /// <summary>
        /// There are no comments for Vehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> Vehicles
        {
            get
            {
                if ((this._Vehicles == null))
                {
                    this._Vehicles = base.CreateQuery<global::Api.Models.Vehicle>("Vehicles");
                }
                return this._Vehicles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Vehicle> _Vehicles;
        /// <summary>
        /// There are no comments for Categories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCategories(global::Api.Models.Category category)
        {
            base.AddObject("Categories", category);
        }
        /// <summary>
        /// There are no comments for Producers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToProducers(global::Api.Models.Manufacturer manufacturer)
        {
            base.AddObject("Producers", manufacturer);
        }
        /// <summary>
        /// There are no comments for Vehicles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToVehicles(global::Api.Models.Vehicle vehicle)
        {
            base.AddObject("Vehicles", vehicle);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"OData ServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
        /// <summary>
        /// There are no comments for GetTaxRateByCountry in the schema.
        /// </summary>
        public virtual global::Microsoft.OData.Client.DataServiceQuerySingle<double> GetTaxRateByCountry(string Country)
        {
            return this.CreateFunctionQuerySingle<double>("", "GetTaxRateByCountry", false, new global::Microsoft.OData.Client.UriOperationParameter("Country", Country));
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for VehicleCounts in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<global::System.Linq.IQueryable_1OfVehicleCountForCategory> VehicleCounts(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Category> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuerySingle<global::System.Linq.IQueryable_1OfVehicleCountForCategory>("Default.VehicleCounts", false);
        }
        /// <summary>
        /// There are no comments for CalculateVehicleAge in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<global::System.Linq.IQueryable_1OfYearForVehicle> CalculateVehicleAge(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Api.Models.Category> _source, int ManufacturerId, int Year)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuerySingle<global::System.Linq.IQueryable_1OfYearForVehicle>("Default.CalculateVehicleAge", false, new global::Microsoft.OData.Client.UriOperationParameter("ManufacturerId", ManufacturerId),
                    new global::Microsoft.OData.Client.UriOperationParameter("Year", Year));
        }
        /// <summary>
        /// There are no comments for TotalVehiclesByCategory in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<int> TotalVehiclesByCategory(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Api.Models.Category> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<int>(_source.Context, _source.AppendRequestUri("Default.TotalVehiclesByCategory"));
        }
        /// <summary>
        /// There are no comments for TotalCategoryCount in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<int> TotalCategoryCount(this global::Microsoft.OData.Client.DataServiceQuery<global::Api.Models.Category> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<int>(_source.Context, _source.AppendRequestUri("Default.TotalCategoryCount"));
        }
        /// <summary>
        /// There are no comments for VehicleCountByManufacturer in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<int> VehicleCountByManufacturer(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Api.Models.Category> _source, int ManufacturerId)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<int>(_source.Context, _source.AppendRequestUri("Default.VehicleCountByManufacturer"), new global::Microsoft.OData.Client.BodyOperationParameter("ManufacturerId", ManufacturerId));
        }
        /// <summary>
        /// There are no comments for VehicleCountByYearManufacturer in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<int> VehicleCountByYearManufacturer(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Api.Models.Category> _source, int ManufacturerId, int Year)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<int>(_source.Context, _source.AppendRequestUri("Default.VehicleCountByYearManufacturer"), new global::Microsoft.OData.Client.BodyOperationParameter("ManufacturerId", ManufacturerId),
                    new global::Microsoft.OData.Client.BodyOperationParameter("Year", Year));
        }
        /// <summary>
        /// There are no comments for VehicleHpByManufacturer in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<int> VehicleHpByManufacturer(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Api.Models.Category> _source, global::Api.Models.OData.Actions.ActionForCategory ActionForCategory)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<int>(_source.Context, _source.AppendRequestUri("Default.VehicleHpByManufacturer"), new global::Microsoft.OData.Client.BodyOperationParameter("ActionForCategory", ActionForCategory));
        }
    }
}
